### PR TITLE
Migrate to use pyproject.toml as much as possible

### PR DESCRIPTION
**Pull request by henrikhorluck**
- Also migrate to use min. Pytrhon v3.9, otherwise most visible change
  is that we now have specific versions of especially dev-dependencies
  vs. "*"-requirements used earlier
- All related e.g. CI and Dockerfile has also been updated

### CODE REVIEW

**Review by COM8 — APPROVED** [review]
Well done. Thank!

**Comment by COM8** [comment]
Looks like the CI is missing some packages like `mypy`.

**Comment by henrikhorluck** [comment]
> Looks like the CI is missing some packages like `mypy`.

Hmm, I am guessing that‘s because Poetry but default installs the packages in a virtualenv, which isn‘t activated, will fix.

**Comment by henrikhorluck** [comment]
@COM8 this should now be ready 2 merge

**Review by COM8 — APPROVED** [review]
Thanks!

**Pull request merged**
