### PR TITLE
Resolves issue #24 #25

### PR DESCRIPTION
**Pull request by lukasdenk**
includes PR #34 and #33.
resolves Issues #24 and #25

I solved both issues in one PR since solving issue #24 and #25 both requested major changes to the testing module. These changes were strongly intermingled. Hence, if I would have created an own PR for one issue and then for the other one, the second PR would have had to discard many of the changes made in the first PR.

### How this PR solves #25:

see PR #33

### How this PR solves #24:
The `StudentenwerkMenuParser` had several issues:
- It parsed all menus except for the mensa in Garching or the Leopoldstr with the prices for the canteen in Weihenstephan and the Lothstraße. The reason was that the following line was meant to be true for all locations with the self-service prices from [here](https://www.studentenwerk-muenchen.de/mensa/mensa-preise/):
```
if "Self-Service" in dish[0] or location == "mensa-garching":
```
However, dish[0] always contains the location and never Self-Service. Somehow, the webpage must have changed.
- Non-Vegan soups and stews were not assigned the per-unit-price of the category "vegan, stew, soup". This PR checks whether a dish is of type "Studitopf". If so, it applies the per-unit-price of the aforementioned category.
- The prices of the different categories were often used as if they were static. However, some code lines changed these prices. Naturally, this lead to wrong price predictions.
Here is the probematic code:
```
            if dish[4] == "0":  # Meat
                prices: Prices = StudentenwerkMenuParser.prices_self_service_classic
                # Add a base price to the dish
                if "Fi" in dish[2]:  # Fish
                    prices.setBasePrice(StudentenwerkMenuParser.prices_self_service_base[2])
                else:  # Sausage and meat. TODO: Find a way to distinguish between sausage and meat
                    prices.setBasePrice(StudentenwerkMenuParser.prices_self_service_base[1])
                return prices
            if dish[4] == "1":  # Vegetarian
                return StudentenwerkMenuParser.prices_self_service_classic
            if dish[4] == "2":  # Vegan
                return StudentenwerkMenuParser.prices_self_service_vegan
```
In this PR, each access to the prices of a category creates a new `Prices` object.

### Adjusting the testing module:
Furthermore, the `test_menu_parser` was adjusted to the new prices.

### CODE REVIEW

**Review by COM8 — APPROVED** [review]
Nice changes. Is This PR ready?

**Comment by lukasdenk** [comment]
Thanks :). It is ready now.

**Comment by COM8** [comment]
Could you please squash all commits where you repeated the same message multiple times?

**Comment by lukasdenk** [comment]
I squashed the commits now. I needed to redo some merges because it is (as I understood) impossible to squash commits when they come before a merge.
But all tests are OK, pre-commit also and git says there are no differences to the old branch.

So- READY TO PULL

**Review by COM8 — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
