### PR TITLE
eat-api version 2

### PR DESCRIPTION
**Pull request by COM8**
This aims to restructure the API to make it easier to get access to all required information at once.

This should address #10.

#### TODO
- [x] Remove the `mensa-garching.json` folder
- [x] Update to the new prices: https://www.studentenwerk-muenchen.de/mensa/mensa-preise/
    - [x] Mensa Leopoldstraße
    - [x] Mensa Weihenstephan and Mensa Lothstraße 
    - [x] Self-Service
- [x] Check if the Self-Service prices match for `mensa-garching` with the actual prices displayed on-site: Not perfect, but works.
- [x] Fix unit tests
- [x] Change the pricing model to student, staff and guests
- [x] Update CI/CD
- [x] Add canteens.json - a list of all canteens with their location #3 
- [x] Update README.md to reflect the changes and add example

### Examples
The new dish object looks like this:
```JSON
"dishes": [
    {
        "name": "Ravioli mit Pilzfüllung in pikanter Kräutersauce",
        "prices": {
            "students": {
                "base_price": 1.0,
                "price_per_unit": 0.75,
                "unit": "100g"
            },
            "staff": {
                "base_price": 1.0,
                "price_per_unit": 0.9,
                "unit": "100g"
            },
            "guests": {
                "base_price": 1.0,
                "price_per_unit": 1.05,
                "unit": "100g"
            }
        },
        "ingredients": [
            "Ei",
            "Gl",
            "GlW",
            "Kn",
            "Mi",
            "Sl"
        ],
        "dish_type": "Pasta"
    }
]
```

And for canteens without different pricing tiers:
```JSON
"dishes": [
    {
        "name": "Tagessuppe",
        "prices": {
            "students": {
                "base_price": 1.0,
                "price_per_unit": null,
                "unit": null
            },
            "staff": {
                "base_price": 1.0,
                "price_per_unit": null,
                "unit": null
            },
            "guests": {
                "base_price": 1.0,
                "price_per_unit": null,
                "unit": null
            }
        },
        "ingredients": [
            "Gl",
            "Sl"
        ],
        "dish_type": "Tagesgericht"
    },
    {
        "name": "(*) Wirsing-Curry mit Kurkuma CousCous",
        "prices": {
            "students": {
                "base_price": 4.5,
                "price_per_unit": null,
                "unit": null
            },
            "staff": {
                "base_price": 4.5,
                "price_per_unit": null,
                "unit": null
            },
            "guests": {
                "base_price": 4.5,
                "price_per_unit": null,
                "unit": null
            }
        },
        "ingredients": [
            "Gl",
            "Mi",
            "Sl"
        ],
        "dish_type": "Tagesgericht"
    },
    {
        "name": "Pasta Front-Cooking Maccaroni Cheese mit Tomatenstücke",
        "prices": {
            "students": {
                "base_price": 4.9,
                "price_per_unit": null,
                "unit": null
            },
            "staff": {
                "base_price": 4.9,
                "price_per_unit": null,
                "unit": null
            },
            "guests": {
                "base_price": 4.9,
                "price_per_unit": null,
                "unit": null
            }
        },
        "ingredients": [
            "Ei",
            "Gl",
            "Mi",
            "Sf",
            "Sl"
        ],
        "dish_type": "Tagesgericht"
    }
]
```

### CODE REVIEW

**Comment by COM8** [comment]
Once merged we have can update GitHub-Pages to the new prices.

**Comment by jpbernius** [comment]
This breaks all existing API consumers!

**Comment by COM8** [comment]
Yes.

**Comment by COM8** [comment]
I created issues for all projects I know about that use eat-api.
* [FMeat.php](https://github.com/jpbernius/FMeat.php/issues/124)
* [UWP-TUM-Campus-App](https://github.com/COM8/UWP-TUM-Campus-App/issues/20)
* [lunch gfz](https://gitlab.com/raabf/lunchgfz-telegram/issues/1)

The plan is to switch to the new format on the **01.01.2020**.
Are there any concern about that?

**Pull request merged**
