### PR TITLE
Improvements of the GH-Pages Website

### LINKED ISSUE #27: Webseite improvements
We should improve the Website (https://tum-dev.github.io/eat-api/):
* Updated theme (and dark mode ?)
* Allow switching between weeks
* Option to show the current day instead of the current week
* Fix showing dishes for the wrong week sometimes
* Perhaps an OpenStreetMap integration for showing dishes

Example:
image

### PR DESCRIPTION
**Pull request by Philipp000**
This is an approach to fix #27 

The following points are included:
- Added darkmode to switch automatically
- Shows the current day instead of the full week
- Fixed wrong week selection
- Updated the design of the canteen selection and date selection

So far the theme is about the same as before, as I wasn't sure on how to update it. Should it be based on Bulma or another CSS framework?

There is also no Open Street Map integration yet, as i wasn't sure where and when to show it.

### CODE REVIEW

**Comment by Philipp000** [comment]
Since I used the same js framework as before, there is no need to bundle anything.
You can watch the website, by serving the branch content with a simple web server.

This is how the page now looks like, when accessing via desktop:
Bildschirmfoto 2021-11-04 um 10 52 52

Additionally, when I included a dark mode version of Bulma, which will switch to dark colors when requested by the browser:
Bildschirmfoto 2021-11-04 um 10 53 11

I also moved the Hint for API-usage to the bottom of the page, as it becomes more accessible I'd say.

Do you think there are further design changes required?

**Comment by COM8** [comment]
Nice one!
How does your new design handle tablets and phones?

**Comment by COM8** [comment]
Perhaps we could add ingredients if available.
What do you think?

**Comment by Philipp000** [comment]
The page is also mobile friendly, and responsive:
IMG_3489

The ingredients are a good idea. I think it would be good to show them, and add the labels/explanations (via a popover) from the documentation on the main branch.
Maybe we could also add images, like in the provided image of the issue.

**Comment by COM8** [comment]
Perhaps somethink like I did in the Windows app:
ingredients
https://github.com/TUM-Dev/Campus-UWP/blob/25e178e1544cfc74474e91d3c10fcc2554d0bef9/ExternalData/Classes/Manager/DishManager.cs#L41-L102
https://github.com/TUM-Dev/Campus-UWP/blob/25e178e1544cfc74474e91d3c10fcc2554d0bef9/UI/Strings/en-US/Resources.resw#L142-L288

**Comment by Philipp000** [comment]
I have now included the same icons and the same descriptions as in the mentioned Campus App.

Bildschirmaufnahme 2021-11-08 um 16 39 44

**Comment by COM8** [comment]
Oh, wow!
Well done. This looks really nice.
Is there anything left to do?

**Review by COM8 — APPROVED** [review]

**Comment by Philipp000** [comment]
I think this should be all, so far.

Once the english translation is available, I could also add a language switcher to the page.

**Pull request merged**
