### PR TITLE
Website language switcher

### PR DESCRIPTION
**Pull request by Philipp000**
As we have now an english version available for the dish titles, I added a language switcher to the website.
Additionally, the language gets prepended to the url of the website.

Currently, only the dish titles are translated, do you think, we should translate the other parts of the website as well?
For the ingredients for example, there should be a solution possible, when the new enums are available from #48.

The current design looks like this:
Bildschirmaufnahme 2021-11-20 um 13 56 36

### CODE REVIEW

**Comment by COM8** [comment]
Looks nice!
Yes, translating the rest of the website would be nice.
Also how/where (at the beginning or end) do you represent the language in the URL?
Couldn't we also auto detect the system language and redirect the user there when he opens the website for the first time?

**Comment by COM8** [comment]
Btw. since the PR is still WIP, could you transform it to a draft PR, so I have an overview about which PRs are ready for review?

**Comment by Philipp000** [comment]
> Looks nice! Yes, translating the rest of the website would be nice. Also how/where (at the beginning or end) do you represent the language in the URL? Couldn't we also auto detect the system language and redirect the user there when he opens the website for the first time?

Alright, I will work on it. For the translation i thought about using the library i18niext, there should be also a feature, for auto-detection of the user language.

The URL of our webpage contains a pseudo path segment for example: #!/mensa-garching
For the language, I just added a de or en in front of that. So a possible path is: #!/de/mensa-garching or #!/de/mensa-garching/2021-11-19 or #!/en/mensa-garching/2021-11-19.
The URL without a date will always represent the current day.

**Comment by COM8** [comment]
> Alright, I will work on it. For the translation i thought about using the library i18niext, there should be also a feature, for auto-detection of the user language.

Yes, sound good. I only heard good stuff about this lib.

The URL format also looks good.

**Comment by Philipp000** [comment]
I have now implemented the translation of the other texts on the website.
Further, I have also included the automatic language detection.

The only thing missing, are the ingredients. However, I think, these can be better managed through a `ingredients.json`, as already mentioned in #48.

Shall I let this PR further on Draft, and continue, once there is an `ingredients.json`, or how should I ideally proceed?

**Comment by COM8** [comment]
In this case I think we should keep it as a draft, since we are waiting for #48.

**Comment by Philipp000** [comment]
This PR is now based on the new JS modules.
I have restored the full functionality, and added the translations for the labels.

Further, I realized that having only the relative path per language available in in the `languages.json` (field `base_url`) and opened #95.

The PR is complete, but I will only make it ready for review, once #95 is merged.

**Comment by Philipp000** [comment]
This is now rebased on the latest version and ready for review

**Review by COM8 — APPROVED** [review]
Thanks. Nice feature.

**Pull request merged**
