### PR TITLE
[Website] Add queue status to website

### PR DESCRIPTION
**Pull request by Philipp000**
This PR adds the current queue status to the website.

Therefore, it fetches data from the provided API.
The result will look as follows:
Bildschirmfoto 2022-01-26 um 18 37 22

Based on the occupancy rate, the color is selected as follows:
- 0-33 percent: green
- 33-66 percent: yellow
- above 66 percent: red

Further, as there is currently CORS rejection, first this PR has to be merged, in order to function properly: https://github.com/dieliste/mensa/pull/9
However, it will not break, when there is CORS or another error, but just not show the progress bar.

### CODE REVIEW

**Comment by COM8** [comment]
When trying this locally I'm getting:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mensa.liste.party/api. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.
```

I'm using `python3 -m http.server` as a simple test web server.

**Comment by COM8** [comment]
> When trying this locally I'm getting:
> 
> ```
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mensa.liste.party/api. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.
> ```
> 
> I'm using `python3 -m http.server` as a simple test web server.

Never mind. I should have read your complete PR first...

**Comment by Philipp000** [comment]
The queue API is now updated and includes the CORS header.
However, there is still a problem, which can be fixed through PR #119 
Currently, the api reference points to 301 redirect, which a browser can't follow, because there is now CORS header present.
After merging the corresponding PR and then after an update of the `canteens.json` the queue status should work properly.

Additionally, I will include the tooltip on hovering.
Another idea I have is: I could show the progress only, when a canteen is open. With #115 that information should be available.

**Comment by Philipp000** [comment]
This is now ready for review.
The queue status will only be shown, when the canteen is currently open

**Comment by COM8** [comment]
The combination of no dishes found and the queue status showing looks kind of broken to me. Perhaps we should introduce some margins here between the queue status and the text?
image

**Comment by Philipp000** [comment]
I have now added a small margin there:
image

Typically, this problem should not occur, as there should be always a menu, when the queue status is shown.

**Review by COM8 — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
