### PR TITLE
Further website improvments

### PR DESCRIPTION
**Pull request by Philipp000**
This fixes the additional errors mentioned in: https://github.com/TUM-Dev/eat-api/issues/27#issuecomment-966098746
Except for the date error, which is fixed together with the removal of moment.js in #55 

The ingredients below each dish are now clickable and show a modal with only the given ingredients
Bildschirmaufnahme 2021-11-18 um 14 26 42

Additionally, there is now wrapping for the ingredients below the dishes on safari browsers as well.

### CODE REVIEW

**Review by COM8 — APPROVED** [review]
Looks good. Thanks.
Please resolve the outstanding conflicts and we are ready to go 🎉.

**Comment by Philipp000** [comment]
It should be now ready for a merge

**Review by COM8 — APPROVED** [review]

**Comment by COM8** [comment]
Still has some conflicts with master.

**Comment by Philipp000** [comment]
Where can I see/fix those?
Here it says, there are no more conflicts. 
Btw. it should be the gh-pages branch, and not the master branch.

image

**Comment by COM8** [comment]
Seams to be working now 🤷‍♂️.

**Pull request merged**
