### PR TITLE
Website - JS Modules

### PR DESCRIPTION
**Pull request by Philipp000**
This PR also includes #82, as it would require further refactoring.
Therefore, this version also is based on the labels for ingredients.

Further, it introduces a module structure, to split code into more readable parts.
Basically, there are three different folders:
- `components` include UI components based on mithril
- `lib` external libraries + module file to load it via import
- `modules` further helper functions

Additionally, I edited the configuration files accordingly.
As this is a big refactoring, and other changes will have to be adopted accordingly, it would be great, if it gets merged soon.
Further, I would base my further changes on this PR.

### CODE REVIEW

**Review by COM8 — APPROVED** [review]
As far as I can say, this looks good.
Thanks!

**Comment by Philipp000** [comment]
I just saw, that there was a conflict with the `app.js` so I rebased this, so that it should be mergeable

**Comment by Philipp000** [comment]
I just saw, that it’s apparently not working again in the Live system…
Unfortunately I can‘t reproduce this behavior locally, and I can only look into it later this evening…

**Comment by COM8** [comment]
Arg...
I also tested it locally and it worked for me too.

```
 Loading failed for the <script> with source “https://tum-dev.github.io/eat-api/js/lib/leaflet.js”. eat-api:13:1
20:12:29.155 Loading module from “https://tum-dev.github.io/eat-api/js/lib/mithril.module.js” was blocked because of a disallowed MIME type (“text/html”).
eat-api
20:12:29.155 Loading failed for the module with source “https://tum-dev.github.io/eat-api/js/lib/mithril.module.js”. eat-api:39:1
20:12:29.286 Loading failed for the module with source “https://tum-dev.github.io/eat-api/js/modules/date-utils.js”. eat-api:39:1
20:12:29.294 Loading failed for the module with source “https://tum-dev.github.io/eat-api/js/components/labels.js”. eat-api:39:1
20:12:29.296 Loading failed for the module with source “https://tum-dev.github.io/eat-api/js/modules/url-utils.js”. eat-api:39:1
20:12:29.296 Loading module from “https://tum-dev.github.io/eat-api/js/lib/leaflet.module.js” was blocked because of a disallowed MIME type (“text/html”).
eat-api
20:12:29.298 Loading failed for the module with source “https://tum-dev.github.io/eat-api/js/lib/leaflet.module.js”.
```

**Pull request merged**
